apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-scanner-db-pvc
  namespace: food-token-scanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-scanner-uploads-pvc
  namespace: food-token-scanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-scanner-qr-pvc
  namespace: food-token-scanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
